name: Fuzz Build

on:
  push:
    branches: [ slikube-enhancement, master, Fuzzing ]
  pull_request:
     branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    - name: Fuzzing methods to find errors.
      run: |
        python fuzz.py
